version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    volumes:
      - /opt/llm_models/llama.cpp:/app/llama.cpp
    command: [ "./entrypoint.sh" ]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
